#!/usr/bin/env bash

if ! command -v clj-kondo &> /dev/null
then
    echo "clj-kondo could not be found. Please follow the installation instructions here https://github.com/clj-kondo/clj-kondo/blob/master/doc/install.md."
    exit 2
fi

array=( $@ )
len=${#array[@]}
_level=${1}
_files=${array[@]:1:$len}

if !(clj-kondo --fail-level $_level --lint $_files)
then
    echo
    echo "Error: new clj-kondo errors found. Please fix them and retry the commit."
    exit 1
fi
