#!/usr/bin/env bash

if ! command -v zprint &> /dev/null
then
    echo "zprint could not be found. Please follow the installation instructions here https://github.com/kkinnear/zprint/blob/main/doc/using/files.md"
    exit 2
fi

zprint -w $@
